// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.ObjectPropertyCatalog;
import com.java.styles.app.domain.ObjectPropertyCatalogDataOnDemand;
import com.java.styles.app.domain.ObjectPropertyCatalogIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ObjectPropertyCatalogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ObjectPropertyCatalogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ObjectPropertyCatalogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ObjectPropertyCatalogIntegrationTest: @Transactional;
    
    @Autowired
    private ObjectPropertyCatalogDataOnDemand ObjectPropertyCatalogIntegrationTest.dod;
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testCountObjectPropertyCatalogs() {
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", dod.getRandomObjectPropertyCatalog());
        long count = ObjectPropertyCatalog.countObjectPropertyCatalogs();
        Assert.assertTrue("Counter for 'ObjectPropertyCatalog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testFindObjectPropertyCatalog() {
        ObjectPropertyCatalog obj = dod.getRandomObjectPropertyCatalog();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to provide an identifier", id);
        obj = ObjectPropertyCatalog.findObjectPropertyCatalog(id);
        Assert.assertNotNull("Find method for 'ObjectPropertyCatalog' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ObjectPropertyCatalog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testFindAllObjectPropertyCatalogs() {
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", dod.getRandomObjectPropertyCatalog());
        long count = ObjectPropertyCatalog.countObjectPropertyCatalogs();
        Assert.assertTrue("Too expensive to perform a find all test for 'ObjectPropertyCatalog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ObjectPropertyCatalog> result = ObjectPropertyCatalog.findAllObjectPropertyCatalogs();
        Assert.assertNotNull("Find all method for 'ObjectPropertyCatalog' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ObjectPropertyCatalog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testFindObjectPropertyCatalogEntries() {
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", dod.getRandomObjectPropertyCatalog());
        long count = ObjectPropertyCatalog.countObjectPropertyCatalogs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ObjectPropertyCatalog> result = ObjectPropertyCatalog.findObjectPropertyCatalogEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ObjectPropertyCatalog' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ObjectPropertyCatalog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testFlush() {
        ObjectPropertyCatalog obj = dod.getRandomObjectPropertyCatalog();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to provide an identifier", id);
        obj = ObjectPropertyCatalog.findObjectPropertyCatalog(id);
        Assert.assertNotNull("Find method for 'ObjectPropertyCatalog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyObjectPropertyCatalog(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ObjectPropertyCatalog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testMergeUpdate() {
        ObjectPropertyCatalog obj = dod.getRandomObjectPropertyCatalog();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to provide an identifier", id);
        obj = ObjectPropertyCatalog.findObjectPropertyCatalog(id);
        boolean modified =  dod.modifyObjectPropertyCatalog(obj);
        Integer currentVersion = obj.getVersion();
        ObjectPropertyCatalog merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ObjectPropertyCatalog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", dod.getRandomObjectPropertyCatalog());
        ObjectPropertyCatalog obj = dod.getNewTransientObjectPropertyCatalog(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ObjectPropertyCatalog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ObjectPropertyCatalog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ObjectPropertyCatalogIntegrationTest.testRemove() {
        ObjectPropertyCatalog obj = dod.getRandomObjectPropertyCatalog();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectPropertyCatalog' failed to provide an identifier", id);
        obj = ObjectPropertyCatalog.findObjectPropertyCatalog(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ObjectPropertyCatalog' with identifier '" + id + "'", ObjectPropertyCatalog.findObjectPropertyCatalog(id));
    }
    
}
