// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.StyleClass;
import com.java.styles.app.domain.StyleClassDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect StyleClassDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StyleClassDataOnDemand: @Component;
    
    private Random StyleClassDataOnDemand.rnd = new SecureRandom();
    
    private List<StyleClass> StyleClassDataOnDemand.data;
    
    public StyleClass StyleClassDataOnDemand.getNewTransientStyleClass(int index) {
        StyleClass obj = new StyleClass();
        setName(obj, index);
        return obj;
    }
    
    public void StyleClassDataOnDemand.setName(StyleClass obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public StyleClass StyleClassDataOnDemand.getSpecificStyleClass(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StyleClass obj = data.get(index);
        Long id = obj.getId();
        return StyleClass.findStyleClass(id);
    }
    
    public StyleClass StyleClassDataOnDemand.getRandomStyleClass() {
        init();
        StyleClass obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StyleClass.findStyleClass(id);
    }
    
    public boolean StyleClassDataOnDemand.modifyStyleClass(StyleClass obj) {
        return false;
    }
    
    public void StyleClassDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StyleClass.findStyleClassEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StyleClass' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StyleClass>();
        for (int i = 0; i < 10; i++) {
            StyleClass obj = getNewTransientStyleClass(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
