// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.Family;
import com.java.styles.app.domain.FamilyDataOnDemand;
import com.java.styles.app.domain.FamilyIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FamilyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FamilyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FamilyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FamilyIntegrationTest: @Transactional;
    
    @Autowired
    private FamilyDataOnDemand FamilyIntegrationTest.dod;
    
    @Test
    public void FamilyIntegrationTest.testCountFamilys() {
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = Family.countFamilys();
        Assert.assertTrue("Counter for 'Family' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FamilyIntegrationTest.testFindFamily() {
        Family obj = dod.getRandomFamily();
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = Family.findFamily(id);
        Assert.assertNotNull("Find method for 'Family' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Family' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FamilyIntegrationTest.testFindAllFamilys() {
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = Family.countFamilys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Family', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Family> result = Family.findAllFamilys();
        Assert.assertNotNull("Find all method for 'Family' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Family' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FamilyIntegrationTest.testFindFamilyEntries() {
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = Family.countFamilys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Family> result = Family.findFamilyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Family' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Family' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FamilyIntegrationTest.testFlush() {
        Family obj = dod.getRandomFamily();
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = Family.findFamily(id);
        Assert.assertNotNull("Find method for 'Family' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFamily(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Family' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FamilyIntegrationTest.testMergeUpdate() {
        Family obj = dod.getRandomFamily();
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = Family.findFamily(id);
        boolean modified =  dod.modifyFamily(obj);
        Integer currentVersion = obj.getVersion();
        Family merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Family' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FamilyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        Family obj = dod.getNewTransientFamily(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Family' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Family' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Family' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FamilyIntegrationTest.testRemove() {
        Family obj = dod.getRandomFamily();
        Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = Family.findFamily(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Family' with identifier '" + id + "'", Family.findFamily(id));
    }
    
}
