// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.FamilyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FamilyDataOnDemand_Roo_Configurable {
    
    declare @type: FamilyDataOnDemand: @Configurable;
    
}
