// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.ObjectPropertyCatalog;
import com.java.styles.app.domain.ObjectPropertyCatalogDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ObjectPropertyCatalogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ObjectPropertyCatalogDataOnDemand: @Component;
    
    private Random ObjectPropertyCatalogDataOnDemand.rnd = new SecureRandom();
    
    private List<ObjectPropertyCatalog> ObjectPropertyCatalogDataOnDemand.data;
    
    public ObjectPropertyCatalog ObjectPropertyCatalogDataOnDemand.getNewTransientObjectPropertyCatalog(int index) {
        ObjectPropertyCatalog obj = new ObjectPropertyCatalog();
        setName(obj, index);
        return obj;
    }
    
    public void ObjectPropertyCatalogDataOnDemand.setName(ObjectPropertyCatalog obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ObjectPropertyCatalog ObjectPropertyCatalogDataOnDemand.getSpecificObjectPropertyCatalog(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ObjectPropertyCatalog obj = data.get(index);
        Long id = obj.getId();
        return ObjectPropertyCatalog.findObjectPropertyCatalog(id);
    }
    
    public ObjectPropertyCatalog ObjectPropertyCatalogDataOnDemand.getRandomObjectPropertyCatalog() {
        init();
        ObjectPropertyCatalog obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ObjectPropertyCatalog.findObjectPropertyCatalog(id);
    }
    
    public boolean ObjectPropertyCatalogDataOnDemand.modifyObjectPropertyCatalog(ObjectPropertyCatalog obj) {
        return false;
    }
    
    public void ObjectPropertyCatalogDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ObjectPropertyCatalog.findObjectPropertyCatalogEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ObjectPropertyCatalog' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ObjectPropertyCatalog>();
        for (int i = 0; i < 10; i++) {
            ObjectPropertyCatalog obj = getNewTransientObjectPropertyCatalog(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
