// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.java.styles.app.domain;

import com.java.styles.app.domain.StyleClass;
import com.java.styles.app.domain.StyleClassDataOnDemand;
import com.java.styles.app.domain.StyleClassIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StyleClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StyleClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StyleClassIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StyleClassIntegrationTest: @Transactional;
    
    @Autowired
    private StyleClassDataOnDemand StyleClassIntegrationTest.dod;
    
    @Test
    public void StyleClassIntegrationTest.testCountStyleClasses() {
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", dod.getRandomStyleClass());
        long count = StyleClass.countStyleClasses();
        Assert.assertTrue("Counter for 'StyleClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StyleClassIntegrationTest.testFindStyleClass() {
        StyleClass obj = dod.getRandomStyleClass();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to provide an identifier", id);
        obj = StyleClass.findStyleClass(id);
        Assert.assertNotNull("Find method for 'StyleClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StyleClass' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StyleClassIntegrationTest.testFindAllStyleClasses() {
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", dod.getRandomStyleClass());
        long count = StyleClass.countStyleClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'StyleClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StyleClass> result = StyleClass.findAllStyleClasses();
        Assert.assertNotNull("Find all method for 'StyleClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StyleClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StyleClassIntegrationTest.testFindStyleClassEntries() {
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", dod.getRandomStyleClass());
        long count = StyleClass.countStyleClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StyleClass> result = StyleClass.findStyleClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StyleClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StyleClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StyleClassIntegrationTest.testFlush() {
        StyleClass obj = dod.getRandomStyleClass();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to provide an identifier", id);
        obj = StyleClass.findStyleClass(id);
        Assert.assertNotNull("Find method for 'StyleClass' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStyleClass(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StyleClass' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StyleClassIntegrationTest.testMergeUpdate() {
        StyleClass obj = dod.getRandomStyleClass();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to provide an identifier", id);
        obj = StyleClass.findStyleClass(id);
        boolean modified =  dod.modifyStyleClass(obj);
        Integer currentVersion = obj.getVersion();
        StyleClass merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StyleClass' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StyleClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", dod.getRandomStyleClass());
        StyleClass obj = dod.getNewTransientStyleClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StyleClass' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StyleClass' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StyleClassIntegrationTest.testRemove() {
        StyleClass obj = dod.getRandomStyleClass();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StyleClass' failed to provide an identifier", id);
        obj = StyleClass.findStyleClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StyleClass' with identifier '" + id + "'", StyleClass.findStyleClass(id));
    }
    
}
